project-utc-develop/routes/web.php
<?php

use App\Http\Controllers\Admin\CartController;
use App\Http\Controllers\Admin\MainController;
use App\Http\Controllers\Admin\MenuController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\SliderController;
use App\Http\Controllers\Admin\UploadController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\Users\LoginController;
use App\Http\Controllers\User\ClientCartController;
use App\Http\Controllers\User\ClientContactController;
use App\Http\Controllers\User\ClientLoginController;
use App\Http\Controllers\User\ClientMainController;
use App\Http\Controllers\User\ClientMenuController;
use App\Http\Controllers\User\ClientProductController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('admin/users/login', [LoginController::class, 'index'])->name('admin.login');
Route::post('admin/users/login/store', [LoginController::class, 'store']);

Route::middleware(['auth'])->group(function () {

    Route::prefix('admin')->group(function () {
        Route::get('/', [MainController::class, 'index'])->name('admin');
        Route::get('main', [MainController::class, 'index']);
        /*Route::get('/', [MainController::class, 'show']);*/
        Route::get('logout', [LoginController::class, 'logout']);

        #Menu
        Route::prefix('menus')->name('menus.')->group(function () {
            Route::get('add', [MenuController::class, 'create'])
                ->middleware('check.permission:create-category')
                ->name('create');
            Route::post('add', [MenuController::class, 'store'])
                ->middleware('check.permission:create-category')
                ->name('store');
            Route::get('list', [MenuController::class, 'index'])
                ->name('list');
            Route::get('edit/{menu}', [MenuController::class, 'show'])
                ->middleware('check.permission:update-category')
                ->name('show');
            Route::post('edit/{menu}', [MenuController::class, 'update'])
                ->middleware('check.permission:update-category')
                ->name('update');
            Route::delete('destroy', [MenuController::class, 'destroy'])
                ->middleware('check.permission:delete-category')
                ->name('destroy');

        });

        #Product
        Route::prefix('products')->name('products.')->group(function () {
            Route::get('add', [ProductController::class, 'create'])
                ->name('create');
            Route::post('add', [ProductController::class, 'store'])
                ->middleware('check.permission:create-product')
                ->name('store');
            Route::get('list', [ProductController::class, 'index'])
                ->name('list');
            Route::get('edit/{product}', [ProductController::class, 'show'])
                ->middleware('check.permission:show-product')
                ->name('show');
            Route::post('edit/{product}', [ProductController::class, 'update'])
                ->middleware('check.permission:update-product')
                ->name('update');
            Route::DELETE('destroy', [ProductController::class, 'destroy'])
                ->middleware('check.permission:delete-product')
                ->name('destroy');
        });

        #Slider
        Route::prefix('sliders')->name('sliders.')->group(function () {
            Route::get('add', [SliderController::class, 'create'])
                ->name('create');
            Route::post('add', [SliderController::class, 'store'])
                ->middleware('check.permission:create-slider')
                ->name('store');
            Route::get('list', [SliderController::class, 'index'])
                ->name('list');
            Route::get('edit/{slider}', [SliderController::class, 'show'])
                ->middleware('check.permission:show-slider')
                ->name('show');
            Route::post('edit/{slider}', [SliderController::class, 'update'])
                ->middleware('check.permission:update-slider')
                ->name('update');
            Route::DELETE('destroy', [SliderController::class, 'destroy'])
                ->middleware('check.permission:delete-slider')
                ->name('destroy');
        });

        #Role
        Route::prefix('roles')->name('roles.')->group(function () {
            Route::get('add', [RoleController::class, 'create'])
                ->name('create');
            Route::post('add', [RoleController::class, 'store'])
                ->middleware('check.permission:create-role')
                ->name('store');
            Route::get('list', [RoleController::class, 'index'])
                ->name('list');
            Route::get('edit/{role}', [RoleController::class, 'edit'])
                ->name('edit')
                ->middleware('check.permission:update-role');
            Route::put('/{role}', [RoleController::class, 'update'])
                ->name('update')
                ->middleware('check.permission:update-role');
            Route::DELETE('destroy', [RoleController::class, 'destroy'])
                ->middleware('check.permission:delete-role')
                ->name('destroy');
        });

        #User in Admin
        Route::prefix('users')->name('users.')->group(function () {
            Route::get('add', [UserController::class, 'create'])
                ->name('create');
            Route::post('add', [UserController::class, 'store'])
                ->middleware('check.permission:create-user')
                ->name('store');
            Route::get('list', [UserController::class, 'index'])
                ->name('list');
            Route::get('edit/{user}', [UserController::class, 'edit'])
                ->name('edit')
                ->middleware('check.permission:update-user');
            Route::put('/{user}', [UserController::class, 'update'])
                ->name('update')
                ->middleware('check.permission:update-user');
            Route::DELETE('destroy', [UserController::class, 'destroy'])
                ->middleware('check.permission:delete-user')
                ->name('destroy');
        });


        #Upload
        Route::post('upload/services', [UploadController::class, 'store']);

        #Cart
        Route::get('customers', [CartController::class, 'index']);
        Route::get('customers/view/{customer}', [CartController::class, 'show'])
            ->middleware('check.role:admin');
        include 'apiAdmin/statistic.php';
    });
});

Route::get('/', [ClientMainController::class, 'index'])->name('client');
Route::post('/services/load-products', [ClientMainController::class, 'loadProduct']);

/*lay ra danh sach san pham*/
Route::get('danh-muc/{id}-{slug}.html', [ClientMenuController::class, 'index']);

/*hien ra chi tiet san pham*/
Route::get('san-pham/{id}-{slug}.html', [ClientProductController::class, 'index']);

/*them gio hang*/
Route::post('/add-cart', [ClientCartController::class, 'index']);
Route::get('carts', [ClientCartController::class, 'show']);
Route::post('update-cart', [ClientCartController::class, 'update']);
Route::get('carts/delete/{id}', [ClientCartController::class, 'remove']);
Route::post('carts', [ClientCartController::class, 'addCart']);

/*login_register client*/
Route::get('user/login', [ClientLoginController::class, 'index']);
Route::post('user/login/store', [ClientLoginController::class, 'store']);
Route::get('user/logout', [ClientLoginController::class, 'logout']);
Route::get('user/register', [ClientLoginController::class, 'register']);
Route::post('user/register/create', [ClientLoginController::class, 'create']);

/*contact*/
Route::get('user/contact', [ClientContactController::class, 'index']);


Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

include "apiAdmin/transaction.php";

project-utc-develop/app/Models/Menu.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Menu extends Model
{
    use HasFactory;

    protected $table = 'categories';

    protected $fillable = [
        'name',
        'parent_id',
        'description',
        'content',
        'thumb',
        'slug',
        'active'
    ];

    /*public function products()
    {
        return $this->hasMany(Product::class, 'menu_id', 'id');
    }*/

    public function products()
    {
        return $this->hasMany(Product::class, 'menu_id', 'product_id');
    }

    public function productAll()
    {
        return $this->belongsToMany(Product::class, 'product_menu', 'menu_id', 'product_id');
    }

    public function scopeWithName($query, $name)
    {
        return $name ? $query->where('name', 'like', '%' . $name . '%') : null;
    }

    public function scopeWithParentId($query, $parentId)
    {
        return $parentId ? $query->where('parent_id', $parentId) : null;
    }

    public function categories()
    {
        return $this->belongsTo(Menu::class, 'parent_id');
    }


    public function children()
    {
        return $this->hasMany(Menu::class, 'parent_id', 'id');
    }

    public function parentCategory()
    {
        return $this->belongsTo(Menu::class, 'parent_id');
    }

    public function scopeAllParent($query)
    {
        return $query->where('parent_id', 0)->with('children');
    }
}

project-utc-develop/app/Http/Controllers/Admin/MenuController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Menu\CreateFormRequest;
use App\Http\Services\Menu\MenuService;
use App\Models\Menu;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;

class MenuController extends Controller
{
    protected $menuService;

    /**
     * @param $menuService
     */
    public function __construct(MenuService $menuService)
    {
        $this->menuService = $menuService;
    }


    public function create()
    {
        return view('admin.menu.add', [
            'title' => 'Thêm Danh Mục Mới',
            'menus' => $this->menuService->getParent()
        ]);
    }

    public function store(CreateFormRequest $request)
    {
        $result =  $this->menuService->create($request);
        if($result) {
            return redirect('/admin/menus/list');
        }
        return redirect()->back();
    }

    public function index(Request $request)
    {
        $menuSearchParent = $this->menuService->all();
        $menus = $this->menuService->search($request);
        return view('admin.menu.list', [
            'title' => 'Danh Sách Danh Mục Mới Nhất',
            'menus' => $menus,
            'menuSearchParent' => $menuSearchParent

        ]);
    }

    public function show(Menu $menu)
    {
        return view('admin.menu.edit', [
            'title' => 'Chỉnh Sửa Danh Mục: ' . $menu->name,
            'menu' => $menu,
            'menus' => $this->menuService->getParent()
        ]);
    }

    public function update(Menu $menu, CreateFormRequest $request)
    {
        $this->menuService->update($request, $menu);
        return redirect('/admin/menus/list');
    }

    public function destroy(Request $request): JsonResponse
    {
        $result = $this->menuService->destroy($request);
        if($result) {
            return response()->json([
               'error' => false,
               'message' => 'Xóa thành công danh mục'
            ]);
        }

        return response()->json([
            'error' => true
        ]);
    }


}

project-utc-develop/resources/views/admin/menu/add.blade.php
@extends('admin.main')

@section('head')
    <script src="/ckeditor/ckeditor.js"></script>
@endsection
@section('content')
    <form action="" method="POST">
        <div class="card-body">
            <div class="form-group">
                <label for="menu">Tên Danh Mục</label>
                <input type="text" name="name" class="form-control" placeholder="Nhập tên danh mục">
                @error('name')
                <div class="form-check text-danger">{{ $message }}</div>
                @enderror
            </div>

            <div class="form-group">
                <label >Danh Mục</label>
                <select class="form-control" name="parent_id">
                    <option value="0">Danh Mục Cha</option>
                    @foreach($menus as $menu)
                        <option value="{{$menu->id}}">{{$menu->name}}</option>
                    @endforeach
                </select>
            </div>

            <div class="form-group">
                <label >Mô Tả</label>
                <textarea name="description" class="form-control"></textarea>
            </div>

            <div class="form-group">
                <label >Mô Tả Chi Tiết</label>
                <textarea name="content" id="content" class="form-control"></textarea>
            </div>

            <div class="form-group">
                <label >Ảnh Sản Phẩm</label>
                <input type="file" name="file" class="form-control" id="upload">
                <div id="image_show">

                </div>
                <input type="hidden" name="thumb" id="thumb">
            </div>


                <div class="form-group">
                    <label>Kích Hoạt</label>
                    <div class="custom-control custom-radio">
                        <input class="custom-control-input" value="1" type="radio" id="active" name="active" checked="">
                        <label for="active" class="custom-control-label">Có</label>
                    </div>
                    <div class="custom-control custom-radio">
                        <input class="custom-control-input" value="0" type="radio" id="no_active" name="active" >
                        <label for="no_active" class="custom-control-label">Không</label>
                    </div>
                </div>
            </div>

        <!-- /.card-body -->

        <div class="card-footer">
            <button type="submit" class="btn btn-primary">Tạo Danh Mục</button>
        </div>
        @csrf
    </form>
@endsection

@section('footer')
    <script>
        CKEDITOR.replace( 'content' );
    </script>
@endsection

project-utc-develop/resources/views/admin/menu/edit.blade.php
@extends('admin.main')

@section('head')
    <script src="/ckeditor/ckeditor.js"></script>
@endsection
@section('content')
    <form action="" method="POST">
        <div class="card-body">
            <div class="form-group">
                <label for="menu">Tên Danh Mục</label>
                <input type="text" name="name" value="{{$menu->name}}" class="form-control" placeholder="Nhập tên danh mục">
            </div>

            <div class="form-group">
                <label >Danh Mục</label>
                <select class="form-control" name="parent_id">
                    <option value="0" {{ $menu->parent_id == 0 ? 'selected' : '' }}>Danh Mục Cha</option>
s                    @foreach($menus as $menuParent)
                        <option value="{{$menuParent->id}}"
                            {{ $menu->parent_id == $menuParent->id ? 'selected' : '' }}>
                            {{$menuParent->name}}</option>
                    @endforeach
                </select>
            </div>

            <div class="form-group">
                <label >Mô Tả</label>
                <textarea name="description" class="form-control">{{ $menu->description }}</textarea>
            </div>

            <div class="form-group">
                <label >Mô Tả Chi Tiết</label>
                <textarea name="content" id="content" class="form-control">{{ $menu->content }}</textarea>
            </div>

            <div class="form-group">
                <label >Ảnh Sản Phẩm</label>
                <input type="file" name="file" class="form-control" id="upload">
                <div id="image_show">
                    <a href="{{$menu->thumb}}" target="_blank">
                        <img src="{{$menu->thumb}}" width="100px">
                    </a>
                </div>
                <input type="hidden" name="thumb" value="{{$menu->thumb}}" id="thumb">
            </div>

            <div class="form-group">
                <label>Kích Hoạt</label>
                <div class="custom-control custom-radio">
                    <input class="custom-control-input" value="1" type="radio" id="active"
                           name="active" {{ $menu->active == 1 ? 'checked=""' : ''}}>
                    <label for="active" class="custom-control-label">Có</label>
                </div>
                <div class="custom-control custom-radio">
                    <input class="custom-control-input" value="0" type="radio" id="no_active"
                           name="active" {{ $menu->active == 0 ? 'checked=""' : ''}}>
                    <label for="no_active" class="custom-control-label">Không</label>
                </div>
            </div>
        </div>

        <!-- /.card-body -->

        <div class="card-footer">
            <button type="submit" class="btn btn-primary">Cập Nhật Danh Mục</button>
        </div>
        @csrf
    </form>
@endsection

@section('footer')
    <script>
        CKEDITOR.replace( 'content' );
    </script>
@endsection

project-utc-develop/resources/views/admin/menu/list.blade.php
@extends('admin.main')

@section('content')
    @php
        $stt = (($_GET['page'] ?? 1) - 1) * 5;
    @endphp
    <div class="col-9 mt-3">
        <form class="form-search" action="{{route('menus.list')}}" method="GET" role="form">
            @csrf
            <div class="row">
                <div class="col-3">
                    <input type="text" class="form-control border card" name="name"
                           value="{{$_GET['name'] ?? ''}}"
                           placeholder="Name" style="padding: 0.5rem 1rem !important;">
                </div>

                <div class="col-3">
                    <button type="submit" class="btn btn-info btn-icon"
                            id="btn-search">
                        <i class="fas fa-search"></i>
                    </button>
                </div>
            </div>
        </form>
    </div>
    <table class="table">
        <thead>
            <tr>
<!--                <th style="width: 50px">ID</th>-->
                <th>Name</th>
                <th>Parent</th>
                <th>Active</th>
                <th>Update</th>
                <th style="width: 200px">&nbsp;</th>
            </tr>
        </thead>
        <tbody>
        @foreach($menus as $menu)
            <tr>
                <td>{{ $menu->name }}</td>
                <td>{{ $menu->categories->name ?? '' }}</td>
                <td>{!! \App\Helpers\Helper::active($menu->active) !!}</td>
                <td>{{ $menu->updated_at }}</td>
                <td>&nbsp;

                    <a class="btn btn-primary btn-sm" href="/admin/menus/edit/{{ $menu->id }}" >
                        <i class="fas fa-edit"></i>
                    </a>

                    <a class="btn btn-danger btn-sm" href="#" onclick="removeRow({{ $menu->id }}, '/admin/menus/destroy')">
                        <i class="fas fa-trash"></i>
                    </a>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
    {{ $menus -> links() }}
@endsection

@section('footer')
    <script>
        CKEDITOR.replace( 'content' );
    </script>
@endsection