project-utc-develop/routes/web.php
<?php

use App\Http\Controllers\Admin\CartController;
use App\Http\Controllers\Admin\MainController;
use App\Http\Controllers\Admin\MenuController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\SliderController;
use App\Http\Controllers\Admin\UploadController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\Users\LoginController;
use App\Http\Controllers\User\ClientCartController;
use App\Http\Controllers\User\ClientContactController;
use App\Http\Controllers\User\ClientLoginController;
use App\Http\Controllers\User\ClientMainController;
use App\Http\Controllers\User\ClientMenuController;
use App\Http\Controllers\User\ClientProductController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('admin/users/login', [LoginController::class, 'index'])->name('admin.login');
Route::post('admin/users/login/store', [LoginController::class, 'store']);

Route::middleware(['auth'])->group(function () {

    Route::prefix('admin')->group(function () {
        Route::get('/', [MainController::class, 'index'])->name('admin');
        Route::get('main', [MainController::class, 'index']);
        /*Route::get('/', [MainController::class, 'show']);*/
        Route::get('logout', [LoginController::class, 'logout']);

        #Menu
        Route::prefix('menus')->name('menus.')->group(function () {
            Route::get('add', [MenuController::class, 'create'])
                ->middleware('check.permission:create-category')
                ->name('create');
            Route::post('add', [MenuController::class, 'store'])
                ->middleware('check.permission:create-category')
                ->name('store');
            Route::get('list', [MenuController::class, 'index'])
                ->name('list');
            Route::get('edit/{menu}', [MenuController::class, 'show'])
                ->middleware('check.permission:update-category')
                ->name('show');
            Route::post('edit/{menu}', [MenuController::class, 'update'])
                ->middleware('check.permission:update-category')
                ->name('update');
            Route::delete('destroy', [MenuController::class, 'destroy'])
                ->middleware('check.permission:delete-category')
                ->name('destroy');

        });

        #Product
        Route::prefix('products')->name('products.')->group(function () {
            Route::get('add', [ProductController::class, 'create'])
                ->name('create');
            Route::post('add', [ProductController::class, 'store'])
                ->middleware('check.permission:create-product')
                ->name('store');
            Route::get('list', [ProductController::class, 'index'])
                ->name('list');
            Route::get('edit/{product}', [ProductController::class, 'show'])
                ->middleware('check.permission:show-product')
                ->name('show');
            Route::post('edit/{product}', [ProductController::class, 'update'])
                ->middleware('check.permission:update-product')
                ->name('update');
            Route::DELETE('destroy', [ProductController::class, 'destroy'])
                ->middleware('check.permission:delete-product')
                ->name('destroy');
        });

        #Slider
        Route::prefix('sliders')->name('sliders.')->group(function () {
            Route::get('add', [SliderController::class, 'create'])
                ->name('create');
            Route::post('add', [SliderController::class, 'store'])
                ->middleware('check.permission:create-slider')
                ->name('store');
            Route::get('list', [SliderController::class, 'index'])
                ->name('list');
            Route::get('edit/{slider}', [SliderController::class, 'show'])
                ->middleware('check.permission:show-slider')
                ->name('show');
            Route::post('edit/{slider}', [SliderController::class, 'update'])
                ->middleware('check.permission:update-slider')
                ->name('update');
            Route::DELETE('destroy', [SliderController::class, 'destroy'])
                ->middleware('check.permission:delete-slider')
                ->name('destroy');
        });

        #Role
        Route::prefix('roles')->name('roles.')->group(function () {
            Route::get('add', [RoleController::class, 'create'])
                ->name('create');
            Route::post('add', [RoleController::class, 'store'])
                ->middleware('check.permission:create-role')
                ->name('store');
            Route::get('list', [RoleController::class, 'index'])
                ->name('list');
            Route::get('edit/{role}', [RoleController::class, 'edit'])
                ->name('edit')
                ->middleware('check.permission:update-role');
            Route::put('/{role}', [RoleController::class, 'update'])
                ->name('update')
                ->middleware('check.permission:update-role');
            Route::DELETE('destroy', [RoleController::class, 'destroy'])
                ->middleware('check.permission:delete-role')
                ->name('destroy');
        });

        #User in Admin
        Route::prefix('users')->name('users.')->group(function () {
            Route::get('add', [UserController::class, 'create'])
                ->name('create');
            Route::post('add', [UserController::class, 'store'])
                ->middleware('check.permission:create-user')
                ->name('store');
            Route::get('list', [UserController::class, 'index'])
                ->name('list');
            Route::get('edit/{user}', [UserController::class, 'edit'])
                ->name('edit')
                ->middleware('check.permission:update-user');
            Route::put('/{user}', [UserController::class, 'update'])
                ->name('update')
                ->middleware('check.permission:update-user');
            Route::DELETE('destroy', [UserController::class, 'destroy'])
                ->middleware('check.permission:delete-user')
                ->name('destroy');
        });


        #Upload
        Route::post('upload/services', [UploadController::class, 'store']);

        #Cart
        Route::get('customers', [CartController::class, 'index']);
        Route::get('customers/view/{customer}', [CartController::class, 'show'])
            ->middleware('check.role:admin');
        include 'apiAdmin/statistic.php';
    });
});

Route::get('/', [ClientMainController::class, 'index'])->name('client');
Route::post('/services/load-products', [ClientMainController::class, 'loadProduct']);

/*lay ra danh sach san pham*/
Route::get('danh-muc/{id}-{slug}.html', [ClientMenuController::class, 'index']);

/*hien ra chi tiet san pham*/
Route::get('san-pham/{id}-{slug}.html', [ClientProductController::class, 'index']);

/*them gio hang*/
Route::post('/add-cart', [ClientCartController::class, 'index']);
Route::get('carts', [ClientCartController::class, 'show']);
Route::post('update-cart', [ClientCartController::class, 'update']);
Route::get('carts/delete/{id}', [ClientCartController::class, 'remove']);
Route::post('carts', [ClientCartController::class, 'addCart']);

/*login_register client*/
Route::get('user/login', [ClientLoginController::class, 'index']);
Route::post('user/login/store', [ClientLoginController::class, 'store']);
Route::get('user/logout', [ClientLoginController::class, 'logout']);
Route::get('user/register', [ClientLoginController::class, 'register']);
Route::post('user/register/create', [ClientLoginController::class, 'create']);

/*contact*/
Route::get('user/contact', [ClientContactController::class, 'index']);


Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

include "apiAdmin/transaction.php";

project-utc-develop/app/Models/Slider.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Slider extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'url',
        'thumb',
        'sort_by',
        'active'
    ];

    public function scopeWithName($query, $name)
    {
        return $name ? $query->where('name', 'like', '%' . $name . '%') : null;
    }
}

project-utc-develop/app/Http/Controllers/Admin/SliderController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Slider\EditSliderRequest;
use App\Http\Requests\Slider\SliderRequest;
use App\Http\Services\Slider\SliderService;
use App\Models\Slider;
use Illuminate\Http\Request;

class SliderController extends Controller
{
    protected $sliderService;

    /**
     * @param $sliderService
     */
    public function __construct(SliderService $sliderService)
    {
        $this->sliderService = $sliderService;
    }


    public function create()
    {
        return view('admin.slider.add', [
            'title' => 'Thêm Slider mới'
        ]);
    }

    public function store(SliderRequest $request)
    {
        $result =  $this->sliderService->insert($request);
        if ($result) {
            return redirect('/admin/sliders/list');
        }
        return redirect()->back();
    }

    public function index(Request $request)
    {
        /*dd($request->input());*/
        $sliders = $this->sliderService->search($request);

        return view('admin.slider.list', [
            'title' => 'Danh Sách Slide Mới Nhất',
            'sliders' => $sliders
        ]);
    }

    public function show(Slider $slider)
    {
        return view('admin.slider.edit', [
            'title' => 'Chỉnh Sửa Slider',
            'slider' => $slider
        ]);
    }

    public function update(EditSliderRequest $request, Slider $slider)
    {
        $result = $this->sliderService->update($request, $slider);

        if ($result) {
            return redirect('/admin/sliders/list');
        }

        return redirect()->back();
    }

    public function destroy(Request $request)
    {
        $result = $this->sliderService->destroy($request);
        if($result) {
            return response()->json([
                'error' => false,
                'message' => 'Xóa thành công Slider'
            ]);
        }
        return response()->json( ['error' => true ]);
    }
}

project-utc-develop/resources/views/admin/slider/add.blade.php
@extends('admin.main')

@section('content')
    <form action="" method="POST">
        <div class="card-body">
            <div class="form-group">
                <label for="product">Tiêu Đề</label>
                <input type="text" name="name" value="{{old('name')}}" class="form-control" >
                @error('name')
                <div class="form-check text-danger">{{ $message }}</div>
                @enderror
            </div>
            <div class="form-group">
                <label for="product">Đường Dẫn</label>
                <input type="text" name="url" value="{{old('url')}}" class="form-control" >
                @error('url')
                <div class="form-check text-danger">{{ $message }}</div>
                @enderror
            </div>

            <div class="form-group">
                <label >Ảnh Sản Phẩm</label>
                <input type="file" name="file" class="form-control" id="upload">
                @error('thumb')
                <div class="form-check text-danger">{{ $message }}</div>
                @enderror
                <div id="image_show">

                </div>
                <input type="hidden" name="thumb" id="thumb">
            </div>

            <div class="form-group">
                <label >Sắp Xếp</label>
                <input type="number" name="sort_by" value="1" class="form-control">
            </div>

            <div class="form-group">
                <label>Kích Hoạt</label>
                <div class="custom-control custom-radio">
                    <input class="custom-control-input" value="1" type="radio" id="active" name="active" checked="">
                    <label for="active" class="custom-control-label">Có</label>
                </div>
                <div class="custom-control custom-radio">
                    <input class="custom-control-input" value="0" type="radio" id="no_active" name="active" >
                    <label for="no_active" class="custom-control-label">Không</label>
                </div>
            </div>
        </div>

        <!-- /.card-body -->
        @hasPermission('create-slider')
        <div class="card-footer">
            <button type="submit" class="btn btn-primary">Tạo Slider</button>
        </div>
        @endhasPermission
        @csrf
    </form>
@endsection

project-utc-develop/resources/views/admin/slider/edit.blade.php
@extends('admin.main')

@section('content')
    <form action="" method="POST">
        <div class="card-body">
            <div class="form-group">
                <label for="product">Tiêu Đề</label>
                <input type="text" name="name" value="{{$slider->name}}" class="form-control" >
                @error('name')
                <div class="form-check text-danger">{{ $message }}</div>
                @enderror
            </div>
            <div class="form-group">
                <label for="product">Đường Dẫn</label>
                <input type="text" name="url" value="{{$slider->url}}" class="form-control" >
                @error('url')
                <div class="form-check text-danger">{{ $message }}</div>
                @enderror
            </div>

            <div class="form-group">
                <label >Ảnh Sản Phẩm</label>
                <input type="file" name="file" class="form-control" id="upload">
                @error('thumb')
                <div class="form-check text-danger">{{ $message }}</div>
                @enderror
                <div id="image_show">
                    <a href="{{$slider->thumb}}" target="_blank">
                        <img src="{{$slider->thumb}}" width="100px">
                    </a>
                </div>
                <input type="hidden" name="thumb" value="{{$slider->thumb}}" id="thumb">
            </div>

            <div class="form-group">
                <label >Sắp Xếp</label>
                <input type="number" name="sort_by" value="{{$slider->sort_by}}" class="form-control">
            </div>

            <div class="form-group">
                <label>Kích Hoạt</label>
                <div class="custom-control custom-radio">
                    <input class="custom-control-input" value="1" type="radio" id="active" name="active"
                    {{$slider->active == 1 ? 'checked' : ''}}>
                    <label for="active" class="custom-control-label">Có</label>
                </div>
                <div class="custom-control custom-radio">
                    <input class="custom-control-input" value="0" type="radio" id="no_active" name="active"
                        {{$slider->active == 0 ? 'checked' : ''}}>
                    <label for="no_active" class="custom-control-label">Không</label>
                </div>
            </div>
        </div>

        <!-- /.card-body -->

        <div class="card-footer">
            <button type="submit" class="btn btn-primary">Cập nhật Slider</button>
        </div>
        @csrf
    </form>
@endsection

project-utc-develop/resources/views/admin/slider/list.blade.php
@extends('admin.main')

@section('content')
    @php
        $stt = (($_GET['page'] ?? 1) - 1) * 5;
    @endphp
    <div class="col-9 mt-3">
        <form class="form-search" action="{{route('sliders.list')}}" method="GET" role="form">
            @csrf
            <div class="row">
                <div class="col-3">
                    <input type="text" class="form-control border card" name="name"
                           value="{{$_GET['name'] ?? ''}}"
                           placeholder="Name" style="padding: 0.5rem 1rem !important;">
                </div>
                <div class="col-3">
                    <button type="submit" class="btn btn-info btn-icon"
                            id="btn-search">
                        <i class="fas fa-search"></i>
                    </button>
                </div>
            </div>
        </form>
    </div>
    <table class="table">
        <thead>
        <tr>
            <th style="width: 50px">ID</th>
            <th>Tiêu Đề</th>
            <th>Link</th>
            <th>Ảnh</th>
            <th>Trạng Thái</th>
            <th>Cập Nhật</th>
            <th style="width: 200px">&nbsp;</th>
        </tr>
        </thead>
        <tbody>
        @foreach($sliders as $key => $slider)
            <tr>
                <td><p style="margin-left: 20px">{{ ++$stt }}</p></td>
                <td>{{ $slider->name }}</td>
                <td>{{ $slider->url}}</td>
                <td>
                    <div id="image_show">
                        <a href="{{$slider->thumb}}" target="_blank">
                            <img src="{{$slider->thumb}}" width="100px">
                        </a>
                    </div>
                </td>

                <td>{!! \App\Helpers\Helper::active($slider->active) !!}</td>
                <td>{{ $slider->updated_at }}</td>
                <td>&nbsp;
                    @hasPermission('update-slider')
                    <a class="btn btn-primary btn-sm" href="/admin/sliders/edit/{{ $slider->id }}">
                        <i class="fas fa-edit"></i>
                    </a>
                    @endhasPermission

                    @hasPermission('delete-slider')
                    <a class="btn btn-danger btn-sm" href="#"
                       onclick="removeRow({{ $slider->id }}, '/admin/sliders/destroy')">
                        <i class="fas fa-trash"></i>
                    </a>
                    @endhasPermission
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>

    {!! $sliders->links() !!}
@endsection