project-utc-develop/routes/web.php
<?php

use App\Http\Controllers\Admin\CartController;
use App\Http\Controllers\Admin\MainController;
use App\Http\Controllers\Admin\MenuController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\SliderController;
use App\Http\Controllers\Admin\UploadController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\Users\LoginController;
use App\Http\Controllers\User\ClientCartController;
use App\Http\Controllers\User\ClientContactController;
use App\Http\Controllers\User\ClientLoginController;
use App\Http\Controllers\User\ClientMainController;
use App\Http\Controllers\User\ClientMenuController;
use App\Http\Controllers\User\ClientProductController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('admin/users/login', [LoginController::class, 'index'])->name('admin.login');
Route::post('admin/users/login/store', [LoginController::class, 'store']);

Route::middleware(['auth'])->group(function () {

    Route::prefix('admin')->group(function () {
        Route::get('/', [MainController::class, 'index'])->name('admin');
        Route::get('main', [MainController::class, 'index']);
        /*Route::get('/', [MainController::class, 'show']);*/
        Route::get('logout', [LoginController::class, 'logout']);

        #Menu
        Route::prefix('menus')->name('menus.')->group(function () {
            Route::get('add', [MenuController::class, 'create'])
                ->middleware('check.permission:create-category')
                ->name('create');
            Route::post('add', [MenuController::class, 'store'])
                ->middleware('check.permission:create-category')
                ->name('store');
            Route::get('list', [MenuController::class, 'index'])
                ->name('list');
            Route::get('edit/{menu}', [MenuController::class, 'show'])
                ->middleware('check.permission:update-category')
                ->name('show');
            Route::post('edit/{menu}', [MenuController::class, 'update'])
                ->middleware('check.permission:update-category')
                ->name('update');
            Route::delete('destroy', [MenuController::class, 'destroy'])
                ->middleware('check.permission:delete-category')
                ->name('destroy');

        });

        #Product
        Route::prefix('products')->name('products.')->group(function () {
            Route::get('add', [ProductController::class, 'create'])
                ->name('create');
            Route::post('add', [ProductController::class, 'store'])
                ->middleware('check.permission:create-product')
                ->name('store');
            Route::get('list', [ProductController::class, 'index'])
                ->name('list');
            Route::get('edit/{product}', [ProductController::class, 'show'])
                ->middleware('check.permission:show-product')
                ->name('show');
            Route::post('edit/{product}', [ProductController::class, 'update'])
                ->middleware('check.permission:update-product')
                ->name('update');
            Route::DELETE('destroy', [ProductController::class, 'destroy'])
                ->middleware('check.permission:delete-product')
                ->name('destroy');
        });

        #Slider
        Route::prefix('sliders')->name('sliders.')->group(function () {
            Route::get('add', [SliderController::class, 'create'])
                ->name('create');
            Route::post('add', [SliderController::class, 'store'])
                ->middleware('check.permission:create-slider')
                ->name('store');
            Route::get('list', [SliderController::class, 'index'])
                ->name('list');
            Route::get('edit/{slider}', [SliderController::class, 'show'])
                ->middleware('check.permission:show-slider')
                ->name('show');
            Route::post('edit/{slider}', [SliderController::class, 'update'])
                ->middleware('check.permission:update-slider')
                ->name('update');
            Route::DELETE('destroy', [SliderController::class, 'destroy'])
                ->middleware('check.permission:delete-slider')
                ->name('destroy');
        });

        #Role
        Route::prefix('roles')->name('roles.')->group(function () {
            Route::get('add', [RoleController::class, 'create'])
                ->name('create');
            Route::post('add', [RoleController::class, 'store'])
                ->middleware('check.permission:create-role')
                ->name('store');
            Route::get('list', [RoleController::class, 'index'])
                ->name('list');
            Route::get('edit/{role}', [RoleController::class, 'edit'])
                ->name('edit')
                ->middleware('check.permission:update-role');
            Route::put('/{role}', [RoleController::class, 'update'])
                ->name('update')
                ->middleware('check.permission:update-role');
            Route::DELETE('destroy', [RoleController::class, 'destroy'])
                ->middleware('check.permission:delete-role')
                ->name('destroy');
        });

        #User in Admin
        Route::prefix('users')->name('users.')->group(function () {
            Route::get('add', [UserController::class, 'create'])
                ->name('create');
            Route::post('add', [UserController::class, 'store'])
                ->middleware('check.permission:create-user')
                ->name('store');
            Route::get('list', [UserController::class, 'index'])
                ->name('list');
            Route::get('edit/{user}', [UserController::class, 'edit'])
                ->name('edit')
                ->middleware('check.permission:update-user');
            Route::put('/{user}', [UserController::class, 'update'])
                ->name('update')
                ->middleware('check.permission:update-user');
            Route::DELETE('destroy', [UserController::class, 'destroy'])
                ->middleware('check.permission:delete-user')
                ->name('destroy');
        });


        #Upload
        Route::post('upload/services', [UploadController::class, 'store']);

        #Cart
        Route::get('customers', [CartController::class, 'index']);
        Route::get('customers/view/{customer}', [CartController::class, 'show'])
            ->middleware('check.role:admin');
        include 'apiAdmin/statistic.php';
    });
});

Route::get('/', [ClientMainController::class, 'index'])->name('client');
Route::post('/services/load-products', [ClientMainController::class, 'loadProduct']);

/*lay ra danh sach san pham*/
Route::get('danh-muc/{id}-{slug}.html', [ClientMenuController::class, 'index']);

/*hien ra chi tiet san pham*/
Route::get('san-pham/{id}-{slug}.html', [ClientProductController::class, 'index']);

/*them gio hang*/
Route::post('/add-cart', [ClientCartController::class, 'index']);
Route::get('carts', [ClientCartController::class, 'show']);
Route::post('update-cart', [ClientCartController::class, 'update']);
Route::get('carts/delete/{id}', [ClientCartController::class, 'remove']);
Route::post('carts', [ClientCartController::class, 'addCart']);

/*login_register client*/
Route::get('user/login', [ClientLoginController::class, 'index']);
Route::post('user/login/store', [ClientLoginController::class, 'store']);
Route::get('user/logout', [ClientLoginController::class, 'logout']);
Route::get('user/register', [ClientLoginController::class, 'register']);
Route::post('user/register/create', [ClientLoginController::class, 'create']);

/*contact*/
Route::get('user/contact', [ClientContactController::class, 'index']);


Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

include "apiAdmin/transaction.php";

project-utc-develop/app/Models/Cart.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Cart extends Model
{
    use HasFactory;

    public $timestamps = false;

    protected $fillable = [
        'customer_id',
        'product_id',
        'pty',
        'price'
    ];

    public function product()
    {
        return $this->hasOne(Product::class, 'id', 'product_id');
    }
}

project-utc-develop/app/Models/Customer.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Customer extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'phone',
        'address',
        'email',
        'content',
        'status'
    ];

    protected $appends = [
        'total_customer'
    ];

    const WAIT = '0';
    const SUCCESS = '1';
    const FAIL = '2';
    const DOING = '3';
    const TEXT_WAIT = 'Chờ xác nhận';
    const TEXT_SUCCESS = 'Giao hàng thành công';
    const TEXT_FAIL = 'Giao hàng thất bại';
    const TEXT_DOING = 'Đang giao';

    public function carts()
    {
        return $this->hasMany(Cart::class, 'customer_id', 'id');
    }

    public function scopeWithName($query, $name)
    {
        return $name ? $query->where('name', 'like', '%' . $name . '%') : null;
    }

    public function scopeWithEmail($query, $email)
    {
        return $email ? $query->where('email', 'like', '%' . $email . '%') : null;
    }

    public function getStatusOrderAttribute()
    {
        if ($this->status == self::WAIT) {
            return self::TEXT_WAIT;
        }
        if ($this->status == self::SUCCESS) {
            return self::TEXT_SUCCESS;
        }
        if ($this->status == self::FAIL) {
            return self::TEXT_FAIL;
        }
        if ($this->status == self::DOING) {
            return self::TEXT_DOING;
        }
    }

    public function scopeWithMonth($query, $month)
    {
        return $month ? $query->whereMonth('created_at', $month) : null;
    }

    public function scopeWithYear($query, $year)
    {
        return $year ? $query->whereYear('created_at', $year) : null;
    }

    public function scopeWithDay($query, $day)
    {
        return $day ? $query->whereDay('created_at', $day) : null;
    }

    public function scopeWithSuccess($query)
    {
        return $query->where('status', self::SUCCESS);
    }

    public function getTotalCustomerAttribute()
    {
        $total = 0;
        if ($this->carts->isNotEmpty()) {
            foreach ($this->carts as $cart) {
                $total += (int)$cart->price * (int)$cart->pty;
            }
        }
        return $total;
    }
}

project-utc-develop/app/Http/Controllers/Admin/CartController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Services\Cart\CartService;
use App\Jobs\UpdateQuantityProductJob;
use App\Models\Customer;
use Illuminate\Http\Request;

class CartController extends Controller
{
    protected $cartService;

    /**
     * @param $cartService
     */
    public function __construct(CartService $cartService)
    {
        $this->cartService = $cartService;
    }

    public function index(Request $request)
    {
        $customers = $this->cartService->search($request);
        return view('admin.cart.customer', [
            'title' => 'Danh Sách Đơn Đặt Hàng',
            'customers' => $customers
        ]);
    }

    public function show(Customer $customer)
    {
        $carts = $this->cartService->getProductForCart($customer);

        return view('admin.cart.detail', [
            'title' => 'Chi Tiết Đơn Hàng: ' . $customer->name,
            'customer' => $customer,
            'carts' => $carts
        ]);
    }

    public function updateStatusOrder(Request $request, Customer $customer)
    {
        $customer->update(['status' => $request->status]);
        if ($request->status == Customer::SUCCESS) {
            $this->dispatch(new UpdateQuantityProductJob($customer));
        }
        return response()->json(['success' => 'Cập nhật trạng thái thành công!!!']);
    }
}

project-utc-develop/resources/views/admin/cart/customer.blade.php
@extends('admin.main')

@section('content')
    @hasRole('admin')
    <div class="col-9 mt-3">
        <form class="form-search" action="{{--{{route('user_list')}}--}}" method="GET" role="form">
            @csrf
            <div class="row">
                <div class="col-3">
                    <input type="text" class="form-control border card" name="name"
                           value="{{$_GET['name'] ?? ''}}"
                           placeholder="Name" style="padding: 0.5rem 1rem !important;">
                </div>
                <div class="col-3">
                    <input type="text" class="form-control border card" name="email"
                           value="{{$_GET['email'] ?? ''}}"
                           placeholder="Email" style="padding: 0.5rem 1rem !important;">
                </div>
                <div class="col-3">
                    <button type="submit" class="btn btn-info text-white btn-icon"
                            id="btn-search">
                        <i class="fas fa-search"></i>
                    </button>
                </div>
            </div>
        </form>
    </div>
    <table class="table">
        <thead>
        <tr>
            <th style="width: 50px">ID</th>
            <th>Tên Khách Hàng</th>
            <th>Số Điện Thoại</th>
            <th>Email</th>
            <th>Trạng thái đơn hàng</th>
            <th>Ngày Đặt</th>
            <th style="width: 200px">&nbsp;</th>
        </tr>
        </thead>
        <tbody>
        @foreach($customers as $key => $customer)
            <tr>
                <td>{{ $customer->id }}</td>
                <td>{{ $customer->name }}</td>
                <td>{{ $customer->phone }}</td>
                <td>{{ $customer->email }}</td>
                <td>
                    <select data-action="{{ route('admin.carts.update-status-cart', $customer->id) }}"
                            class="form-control update-status-ship" style="width: 150px">
                        <option {{ $customer->status == '0' ? 'selected' : '' }} value="0">Chờ xác nhận</option>
                        <option {{ $customer->status == '3' ? 'selected' : '' }} value="3">Đang giao</option>
                        <option {{ $customer->status == '1' ? 'selected' : '' }} value="1">Thành công</option>
                        <option {{ $customer->status == '2' ? 'selected' : '' }} value="2">Thất bại</option>
                    </select>
                </td>
                {{--                <td>{{ $customer->status_order }}</td>--}}
                <td>{{ $customer->created_at }}</td>
                <td>&nbsp;
                    <a class="btn btn-primary btn-sm" href="/admin/customers/view/{{ $customer->id }}">
                        <i class="fas fa-eye"></i>
                    </a>
                    <a class="btn btn-danger btn-sm" href="#"
                       onclick="removeRow({{ $customer->id }}, '/admin/customers/destroy')">
                        <i class="fas fa-trash"></i>
                    </a>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>

    {!! $customers->links() !!}

    @endhasRole
@endsection

@section('footer')
    <script>
        $(document).ready(function () {
            $(document).on('change', '.update-status-ship', function () {
                let URL = $(this).data('action');
                let status = $(this).val();
                $.ajax({
                    url: URL,
                    method: 'POST',
                    data: {
                        status: $(this).val()
                    }
                }).done(function (res) {

                })
            });
        });
    </script>
@endsection

project-utc-develop/resources/views/admin/cart/detail.blade.php
@extends('admin.main')

@section('content')
    <div class="customer mt-3">
        <ul>
            <li>Tên Khách Hàng: <strong>{{$customer->name}}</strong></li>
            <li>Số Điện Thoại: <strong>{{$customer->phone}}</strong></li>
            <li>Địa Chỉ: <strong>{{$customer->address}}</strong></li>
            <li>Email: <strong>{{$customer->email}}</strong></li>
            <li>Trạng thái đơn hàng: <strong>{{$customer->status_order}}</strong></li>
            <li>Ghi Chú: <strong>{{$customer->content}}</strong></li>
        </ul>
    </div>

    <div class="carts">
        @php
            $total = 0;
        @endphp
        <table class="table">
            <tr class="table_head">
                <th class="column-1">IMG</th>
                <th class="column-2">Product</th>
                <th class="column-3">Price</th>
                <th class="column-4">Quantity</th>
                <th class="column-5">Total</th>
                <th class="column-6">&nbsp;</th>
            </tr>
            @foreach($carts as $key => $cart)
                @php
                    $price = $cart->price * $cart->pty;
                    $total += $price;
                @endphp
                <tr >
                    <td class="column-1">
                        <div class="how-itemcart1">
                            <img src="{{$cart->product->thumb}}" alt="IMG" style="width: 100px">
                        </div>
                    </td>
                    <td class="column-2">{{$cart->product->name}}</td>
                    <td class="column-3">{{ number_format($cart->price, 0, '', '.') }}</td>
                    <td class="column-4">{{ $cart->pty }}</td>

                    <td class="column-5">{{number_format($price, 0, '', '.')}}</td>

                </tr>
            @endforeach
                <tr>
                    <td colspan="4" class="text-right">Tổng Tiền</td>
                    <td>{{number_format($total, 0, '', '.')}}</td>
                </tr>
        </table>
    </div>



@endsection

@section('footer')
    <script>
        CKEDITOR.replace('content');
    </script>
@endsection